name: Compile Python with Nuitka

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest]
        installer: [pip, uv]
    name: ${{ matrix.os }}-${{ matrix.installer }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install uv
      if: ${{ matrix.installer }} == 'uv'
      uses: astral-sh/setup-uv@v3
      
    - name: Install Nuitka
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        
    - name: Install pyside6
      run: |
        ${{ matrix.installer=='uv' && 'uv pip install --system' || 'pip install' }} pyside6
    
    - name: Compile main.py
      run: |
        python -m nuitka main.py --assume-yes-for-downloads

    - name: List compiled files
      run: |
        du -ah main.dist | sort -rh >du.txt

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }} ${{ matrix.installer }} du.txt
        path: |
            du.txt
